Student Information Server/MVC-SIS/MVC-SIS_UI/Controllers/AdminController.cs
using MVC_SIS_Data;
using MVC_SIS_Models;
using MVC_SIS_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_SIS_UI.Controllers
{
    public class AdminController : Controller
    {
        //ask about the home controller and how it is not completed. the instructions said nothing about completing the missing views

        [HttpGet]
        public ActionResult Majors()
        {
            var model = MajorRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddMajor()
        {
            return View(new AddEditMajorVM());
        }

        [HttpPost]
        public ActionResult AddMajor(AddEditMajorVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            MajorRepository.Add(viewModel.currentMajor.MajorName);
            return RedirectToAction("Majors");
        }

        [HttpGet]
        public ActionResult EditMajor(int id)
        {
            AddEditMajorVM viewmodel = new AddEditMajorVM();
            viewmodel.currentMajor = MajorRepository.Get(id);
            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult EditMajor(AddEditMajorVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            MajorRepository.Edit(viewModel.currentMajor);
            return RedirectToAction("Majors");
        }

        [HttpGet]
        public ActionResult DeleteMajor(int id)
        {
            DeleteMajorVM viewModel = new DeleteMajorVM();
            viewModel.currentMajor = MajorRepository.Get(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteMajor(DeleteMajorVM viewModel)
        {
            MajorRepository.Delete(viewModel.currentMajor.MajorId);
            return RedirectToAction("Majors");
        }

        [HttpGet]
        public ActionResult States()
        {
            var model = StateRepository.GetAll();
            return View(model.ToList()) ;
        }

        [HttpGet]
        public ActionResult AddState()
        {
            return View(new AddStateVM());
        }

        [HttpPost]
        public ActionResult AddState(AddStateVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            StateRepository.Add(viewModel.currentState);
            return RedirectToAction("States");
        }

        //exercise never explicitly says to create edit state method just to link to it
        [HttpGet]
        public ActionResult EditState(string stateAbbreviation)
        {
            EditStateVM viewModel = new EditStateVM();
            viewModel.currentState = StateRepository.Get(stateAbbreviation);
            viewModel.stateAbbreviationSearchId = stateAbbreviation;
            return View(viewModel);
        }

        //you guys did not make this one simple. following the example above causes it to save the original state abbreviation rather than the new one that is typed in
        [HttpPost]
        public ActionResult EditState(EditStateVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            EditState newState = new EditState();
            newState.StateAbbreviation = viewModel.currentState.StateAbbreviation;
            newState.StateName = viewModel.currentState.StateName;
            newState.searchStateAbbreviation = viewModel.stateAbbreviationSearchId;

            StateRepository.Edit(newState);
            return RedirectToAction("States");
        }

        [HttpGet]
        public ActionResult DeleteState(string stateAbbreviation)
        {
            DeleteStateVM viewModel = new DeleteStateVM();
            viewModel.currentState = StateRepository.Get(stateAbbreviation);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteState(DeleteStateVM viewModel)
        {
            StateRepository.Delete(viewModel.currentState.StateAbbreviation);
            return RedirectToAction("States");
        }

        [HttpGet]
        public ActionResult Courses()
        {
            var model = CourseRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddCourse()
        {
            return View(new AddEditCourseVM());
        }

        [HttpPost]
        public ActionResult AddCourse(AddEditCourseVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            CourseRepository.Add(viewModel.currentCourse.CourseName);
            return RedirectToAction("Courses");
        }

        [HttpGet]
        public ActionResult EditCourse(int id)
        {
            AddEditCourseVM viewmodel = new AddEditCourseVM();
            viewmodel.currentCourse = CourseRepository.Get(id);
            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult EditCourse(AddEditCourseVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            CourseRepository.Edit(viewModel.currentCourse);
            return RedirectToAction("Courses");
        }

        [HttpGet]
        public ActionResult DeleteCourse(int id)
        {
            DeleteCourseVM viewModel = new DeleteCourseVM();
            viewModel.currentCourse = CourseRepository.Get(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult DeleteCourse(DeleteCourseVM viewModel)
        {
            CourseRepository.Delete(viewModel.currentCourse.CourseId);
            return RedirectToAction("Courses");
        }
    }
}

Student Information Server/MVC-SIS/MVC-SIS_UI/Controllers/StudentController.cs
using MVC_SIS_Data;
using MVC_SIS_Models;
using MVC_SIS_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_SIS_UI.Controllers
{
    public class StudentController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            var model = StudentRepository.GetAll();

            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var viewModel = new StudentAddVM();
            viewModel.SetCourseItems(CourseRepository.GetAll());
            viewModel.SetMajorItems(MajorRepository.GetAll());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(StudentAddVM studentVM)
        {
            if (!ModelState.IsValid)
            {
                //had to add the two lines below or the drop down menus would not return
                studentVM.SetCourseItems(CourseRepository.GetAll());
                studentVM.SetMajorItems(MajorRepository.GetAll());
                return View(studentVM);
            }

            studentVM.Student.Courses = new List<Course>();

            foreach (var id in studentVM.SelectedCourseIds)
                studentVM.Student.Courses.Add(CourseRepository.Get(id));

            studentVM.Student.Major = MajorRepository.Get(studentVM.Student.Major.MajorId);

            StudentRepository.Add(studentVM.Student);

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            EditStudentVM viewModel = new EditStudentVM();
            viewModel.Student = StudentRepository.Get(id);         
            viewModel.SetCourseItems(CourseRepository.GetAll());
            viewModel.SetMajorItems(MajorRepository.GetAll());
            viewModel.SetStateItems(StateRepository.GetAll());

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(EditStudentVM viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Student = StudentRepository.Get(viewModel.Student.StudentId);
                viewModel.SetCourseItems(CourseRepository.GetAll());
                viewModel.SetMajorItems(MajorRepository.GetAll());
                viewModel.SetStateItems(StateRepository.GetAll());
                return View(viewModel);
            }

            viewModel.Student.Courses = new List<Course>();

            foreach (var id in viewModel.SelectedCourseIds)
                viewModel.Student.Courses.Add(CourseRepository.Get(id));

            viewModel.Student.Major = MajorRepository.Get(viewModel.Student.Major.MajorId);

            StudentRepository.Edit(viewModel.Student);
            StudentRepository.SaveAddress(viewModel.Student.StudentId, viewModel.Student.Address);
            return RedirectToAction("List");

            throw new NotImplementedException();
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            StudentDeleteVM viewModel = new StudentDeleteVM();
            viewModel.currentStudent = StudentRepository.Get(id);
            return View(viewModel);

            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult Delete(StudentDeleteVM viewModel)
        {
            StudentRepository.Delete(viewModel.currentStudent.StudentId);
            return RedirectToAction("List");

            throw new NotImplementedException();
        }
    }
}

Student Information Server/MVC-SIS/MVC-SIS_UI/Views/Shared/StudentNav.cshtml
<h4>Student Information</h4>
<ul class="nav nav-pills nav-stacked">
    <li>@Html.ActionLink("Student Home", "Index", "Student")</li>
    <li>@Html.ActionLink("Student List", "List", "Student")</li>
</ul>

Student Information Server/MVC-SIS/MVC-SIS_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Student Information System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Students", "Index", "Student")
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Majors", "Majors", "Admin")</li>
                            <li>@Html.ActionLink("States", "States", "Admin")</li>
                            <li>@Html.ActionLink("Courses", "Courses", "Admin")</li>
                        </ul>
                    </li>
                    <li>
                        @Html.ActionLink("About", "About", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home")
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - The Software Guild</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
</body>
</html>