Full-Stack Car Dealership/CarDealership.UI/Controllers/InventoryController.cs
using CarDealership.Data.Factories;
using CarDealership.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.UI.Controllers
{
    public class InventoryController : Controller
    {
        // GET: Vehicle
        public ActionResult Details(int id)
        {        
            var repo = VehicleRepoFactory.GetRepository();
            var model = repo.GetDetails(id);

            return View(model);
        }

        public ActionResult New()
        {
            SearchVM model = new SearchVM();
            model.SearchYears = VehicleRepoFactory.GetRepository().CreateSearchYears().ToList();
            model.PriceRange = VehicleRepoFactory.GetRepository().CreatePriceRange().ToList();
            return View(model);
        }

        public ActionResult Used()
        {
            SearchVM model = new SearchVM();
            model.SearchYears = VehicleRepoFactory.GetRepository().CreateSearchYears().ToList();
            model.PriceRange = VehicleRepoFactory.GetRepository().CreatePriceRange().ToList();
            return View(model);
        }
    }
}

Full-Stack Car Dealership/CarDealership.UI/Controllers/ReportsController.cs
using CarDealership.Data.Factories;
using CarDealership.UI.Models;
using CarDealership.UI.Utitlites;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace CarDealership.UI.Controllers
{
    [Authorize(Roles = "admin")]
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Inventory()
        {
            InventoryReportVM model = new InventoryReportVM();
            model.NewVehicles = VehicleRepoFactory.GetRepository().GetInventoryReport("new").ToList();
            model.UsedVehicles = VehicleRepoFactory.GetRepository().GetInventoryReport("used").ToList();

            return View(model);
        }


        public ActionResult Sales()
        {
            SalesSearchVM model = new SalesSearchVM();
            var userList = AuthorizeUtilities.GetUsersInRole("sales");
            model.Users = from u in userList
                          select new SelectListItem { Text = u.FirstName + ' ' + u.LastName, Value = u.Id.ToString() };

            return View(model);
        }
    }
}

Full-Stack Car Dealership/CarDealership.UI/Controllers/SalesController.cs
using CarDealership.Data.Factories;
using CarDealership.UI.Models;
using CarDealership.UI.Utitlites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.UI.Controllers
{
    [Authorize(Roles = "sales")]
    public class SalesController : Controller
    {
        // GET: Sales    
        public ActionResult Index()
        {
            SearchVM model = new SearchVM();
            model.SearchYears = VehicleRepoFactory.GetRepository().CreateSearchYears().ToList();
            model.PriceRange = VehicleRepoFactory.GetRepository().CreatePriceRange().ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult Purchase(int id)
        {
            if (Request.IsAuthenticated)
            {
                ViewBag.UserID = AuthorizeUtilities.GetUserId(this);
            }

            var repo = VehicleRepoFactory.GetRepository();
            var staterepo = StateRepoFactory.GetRepository();
            var model = new AddPurchaseVM();
            model.VehicleDetails = repo.GetDetails(id);
            model.Purchase.VehicleID = id;
            model.SetStateItems(staterepo.GetAll());
            return View(model);
        }

        [HttpPost]
        public ActionResult Purchase(AddPurchaseVM model)
        {
            if (Request.IsAuthenticated)
            {
                model.Purchase.UserID = AuthorizeUtilities.GetUserId(this);
            }

            if (ModelState.IsValid)
            {
                var customerRepo = CustomerRepoFactory.GetRepository();
                var purchaseRepo = PurchaseRepoFactory.GetRepository();
                try
                {
                    customerRepo.Insert(model.Customer);

                    model.Purchase.CustomerID = model.Customer.CustomerID;
                    model.Purchase.VehicleID = model.VehicleDetails.VehicleID;

                    purchaseRepo.Insert(model.Purchase);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            else
            {
                var repo = VehicleRepoFactory.GetRepository();
                var staterepo = StateRepoFactory.GetRepository();
                
                model.VehicleDetails = repo.GetDetails(model.VehicleDetails.VehicleID);
                model.Purchase.VehicleID = model.VehicleDetails.VehicleID;
                model.SetStateItems(staterepo.GetAll());

                return View(model);
            }
        }

    }
}

Full-Stack Car Dealership/CarDealership.UI/Views/Reports/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-xs-12 col-md-6">
        <h2>Reports</h2>
        <p>@Html.ActionLink("Inventory Report", "Inventory", "Reports", null)</p>
        <p>@Html.ActionLink("Sales Report", "Sales", "Reports", null)</p>
    </div>
</div>

Full-Stack Car Dealership/CarDealership.UI/Views/Reports/Inventory.cshtml
@model CarDealership.UI.Models.InventoryReportVM

@{
    ViewBag.Title = "Inventory";
}


<div class="row">
    <div class="col-xs-12 col-md-6">
        <h2>Inventory Report</h2>
        <table class="table table-bordered table-striped">
            <caption>New Vehicles</caption>
            <thead>
                <tr>
                    <th>Year</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Count</th>
                    <th>Stock Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var vehicle in Model.NewVehicles)
                {
                    <tr>
                        <td>@vehicle.VehicleYear</td>
                        <td>@vehicle.MakeName</td>
                        <td>@vehicle.ModelName</td>
                        <td>@vehicle.Count</td>
                        <td>@vehicle.StockValue</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-md-6">
        <table class="table table-bordered table-striped">
            <caption>Used Vehicles</caption>
            <thead>
                <tr>
                    <th>Year</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Count</th>
                    <th>Stock Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var vehicle in Model.UsedVehicles)
                {
                    <tr>
                        <td>@vehicle.VehicleYear</td>
                        <td>@vehicle.MakeName</td>
                        <td>@vehicle.ModelName</td>
                        <td>@vehicle.Count</td>
                        <td>@vehicle.StockValue</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Full-Stack Car Dealership/CarDealership.UI/Views/Reports/Sales.cshtml
@model CarDealership.UI.Models.SalesSearchVM

@{
    ViewBag.Title = "Sales";
}

<div class="row">
    <div class="col-xs-12 col-md-6">
        <h2>Sales Report</h2>
    </div>
</div>


<div class="row" style="border:1px solid black; padding:20px">
    <div class="col-xs-12">
        <form id="searchForm" class="form-inline">
            <div class="form-group">
                <label for="userID">User</label>
                @Html.DropDownList("userID", Model.Users, "All", new { @class = "form-control", id = "userID" })
            </div>
            <div class="form-group">
                <label for="fromDate">From Date</label>
                <input type="text" class="form-control" id="fromDate">
            </div>
            <div class="form-group">
                <label for="toDate">To Date</label>
                <input type="text" class="form-control" id="toDate">
            </div>
            <button id="btnSearch" class="btn btn-default">Search</button>
        </form>
    </div>
</div>


<div class="row">
    <div id="searchResults" class="col-xs-12">


    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("#searchForm").submit(function (e) {
                search();
                return false;
            });
        });

        function search() {
            var params;
            params = 'userID=' + $('#userID').val() + '&fromDate=' + $('#fromDate').val() + '&toDate=' + $('#toDate').val();

            $.ajax({
                type: 'GET',
                url: 'https://localhost:44305/api/salesReport/search?' + params,
                success: function (results) {
                    $('#searchResults').empty();
                    $('#searchResults').append('<h3>Search Results</h3>' +
                        '<table class="table table-bordered table-striped">' +
                        '<thead><tr>' +
                        '<th>User</th><th>Total Sales</th><th>Total Inventory</th>' +
                        '</tr></thead><tbody></tbody></table>');

                    $.each(results, function(index, user) {
                        var html = '<tr>' +
                       '<td>' + user.FirstName + ' ' + user.LastName + '</td>' +
                       '<td>$' + user.TotalSales.toFixed(2) + '</td>' +
                       '<td>' + user.TotalVehicles + '</td></tr>';

                        $('#searchResults tbody').append(html.toString());
                });
        },
        error: function () {
            alert('Error performing search, try again later!')
        }
        });
        }
    </script>
}